// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAK3NwOxXfSNhLQSc-F1TF_pN4nfe7dWmw',
    appId: '1:332296463958:web:b1a62e4edf7f599631fdf7',
    messagingSenderId: '332296463958',
    projectId: 'wanalearn-245e0',
    authDomain: 'wanalearn-245e0.firebaseapp.com',
    storageBucket: 'wanalearn-245e0.appspot.com',
    measurementId: 'G-3B5H99BLPX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2u0bS9LSC0ruL0NpUoj5t2sEOxy5FEgY',
    appId: '1:332296463958:android:5a224934dd31b70431fdf7',
    messagingSenderId: '332296463958',
    projectId: 'wanalearn-245e0',
    storageBucket: 'wanalearn-245e0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbBEMnZ5_Bby8ogWKig0YV4lixQYINRPQ',
    appId: '1:332296463958:ios:17f35d28436b5a7e31fdf7',
    messagingSenderId: '332296463958',
    projectId: 'wanalearn-245e0',
    storageBucket: 'wanalearn-245e0.appspot.com',
    iosBundleId: 'com.example.wanalearn',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCbBEMnZ5_Bby8ogWKig0YV4lixQYINRPQ',
    appId: '1:332296463958:ios:1d9e7f803e55d0b831fdf7',
    messagingSenderId: '332296463958',
    projectId: 'wanalearn-245e0',
    storageBucket: 'wanalearn-245e0.appspot.com',
    iosBundleId: 'com.example.wanalearn.RunnerTests',
  );
}
